# Generated by Django 5.1.3 on 2025-11-09 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(choices=[('water', 'Water'), ('electricity', 'Electricity'), ('road', 'Road'), ('waste', 'Waste Management'), ('streetlight', 'Street Light'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('gps_coordinates', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('photo', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
